### ISSUE TITLE
Activation fails

### ISSUE THREAD

**Issue by johannesE** [matgargano/vue-wordpress-plugin#3]
I am pretty new to php, so I'm not sure why this plugin seems to work for everyone else. I received the following error upon activation:
![screenshot from 2017-12-05 14-01-48](https://user-images.githubusercontent.com/2607157/33608835-11bdbcfe-d9c6-11e7-91f9-81e0ee4d1a7c.png)
I fixed it by adding `require_once("vwp/enqueues.php");` in the `vwp.php` file.

Should this be the standard or is this due to my setup? I use chassis http://docs.chassis.io/en/latest/ for my local dev environment.

**Comment by matgargano** [comment]
Did you follow all of the steps in the readme -- including running composer install from within the repo's directory?

**Comment by johannesE** [comment]
> Did you follow all of the steps in the readme -- including running composer install from within the repo's directory?

Of course.

**Comment by matgargano** [comment]
I just ran it -- on an arbitrary wordpress installation and it worked without problem. It also seems like this issue is isolated on your end. Composer's autoloader should be doing the inclusion here.

What version of PHP are you using?

What version of Composer?

**Comment by johannesE** [comment]
Locally:
`Composer version 1.5.1 2017-08-09 16:07:22`
`PHP 7.1.11-0ubuntu0.17.10.1`

On the vagrant machine that actually runs it:
`composer not installed` => this might be the issue, but I don't know how composer works. I assumed that it generates some static files which can then be used on any machine.
`PHP 7.0.26-1+ubuntu16.04.1`

If you just close this issue, it's okay for me because I'm not going to need additional php files and the issue is solved via the above `require`-workaround.

One more thing that might be the source of the issue is that I renamed the folder of this plugin (it should have a descriptive name), but i was careful to rename it everywhere (including the name in `composer.json`)

**Comment by matgargano** [comment]
I can't seem to figure out what would be causing this -- if you run into more trouble please let me know. If you want to do a screenshare too I'd be happy to oblige. Let me know. Closing for now @johannesE

**Comment by juwul** [comment]
Same problem here and the fix from OP did work for me! Thanks
