### ISSUE TITLE
Question: how do I include images?

### ISSUE THREAD

**Issue by johannesE** [matgargano/vue-wordpress-plugin#4]
I want to use images in my vue plugin. I should probably add something to the webpack config. Any ideas? I'm asking this here because I'm pretty sure this repo could benefit from a solution.

**Comment by matgargano** [comment]
Let me know if you come up with anything -- and feel free to fork @johannesE  since this is not a bug per-se let's see if anyone wants to help here.

**Comment by johannesE** [comment]
For now I upload the images to wordpress and include them with their path 🙄. Not the best solution, I know..

**Comment by matgargano** [comment]
I'm going to close this, please reopen if you need to
