### ISSUE TITLE
Hot reloading inside WordPress

### ISSUE THREAD

**Issue by madebycaliper** [matgargano/vue-wordpress-plugin#6]
hey I'd love to have a robust Vue dev environment inside WordPress and I've been doing research trying to figure out if there's a way to feather in WP hot reloading to the `vue-cli`/`webpack-hot-middleware` service. have you experimented with that at all? Do you know anyone else who has? Vue is awesome but it's kind of a pain in the ass to develop it without the vue-devtools and hot reloading...trying to figure it out. Thanks.

**Comment by matgargano** [comment]
Sorry - I have not!
